apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tenant.name }}-user
type: Opaque
data:
  CONSOLE_ACCESS_KEY: {{ .Values.default_user.CONSOLE_ACCESS_KEY | b64enc }}
  CONSOLE_SECRET_KEY: {{ .Values.default_user.CONSOLE_SECRET_KEY | b64enc }}
