apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tenant.name }}-kes-client-tls
type: Opaque
data: 
  public.crt: {{ .Values.kes.client.public_crt | b64enc | quote }}
  private.key: {{ .Values.kes.client.private_key | b64enc | quote }}
