{{- if .Values.ingress.tls }}  
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tenant.name }}-ingress-tls
type: Opaque
data: 
  ca.crt: {{ .Values.ingress.tls.ca_crt | b64enc | quote }}
  tls.crt: {{ .Values.ingress.tls.server_crt | b64enc | quote }}
  tls.key: {{ .Values.ingress.tls.server_key | b64enc | quote }}
{{- end }}
