apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tenant.name }}-tls
type: Opaque
data: 
  public.crt: {{ .Values.tls.public_crt | b64enc | quote }}
  private.key: {{ .Values.tls.private_key | b64enc | quote }}
